[project]
name = "plexjanitor"
version = "1.0.2"
description = "clear up plex"
authors = [{ name = "Sander van Dragt", email = "sander@vandragt.com" }]
license = "MIT"
requires-python = ">=3.10"
dependencies = ["plexapi>=4.17.2"]

[dependency-groups]
dev = ["pytest>=8.3.5", "ruff>=0.16.3"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
